### ISSUE TITLE
Full of malware, check before using

### ISSUE THREAD

**Issue by muikeP** [origami-xyz/shitcoin-sniper-bot#1]
https://www.virustotal.com/gui/file/e0c7c03f77f26743d5f3ebc556ddcdead9debe0161a5012f20641b07588862fe/details

![image](https://github.com/origami-xyz/shitcoin-sniper-bot/assets/129886539/edc36373-ef30-4b74-acd2-e2cc93eb5245)

**Comment by origami-xyz** [comment]
It's not malware. I used thread and network classes in the code and also changed the icon on the binary file. Maybe it could trigger antivirus detection.
