### ISSUE TITLE
Dependency check error

### ISSUE THREAD

**Issue by HeroinHazed** [origami-xyz/shitcoin-sniper-bot#2]
System.IO.FileNotFoundException: Could not find file '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/5.0,0/data/FrameworkList.xml 

dont know how to fix this error any suggestions.

**Comment by GHOS7ED** [comment]
Download .Net Framework 4.5

**Comment by klngcaleb** [comment]
i have it installed and still get that error

**Comment by MihaiSMC** [comment]
How did you manage to solve it? I tried to install .Net Framework 4.5, but it says that it or a newer version is already installed.

**Comment by iamtim250** [comment]
same error here as well, tried various things, cannot install .net 4.5 as later versions already installed.

**Comment by prezesov** [comment]
Stucked on "dependency check". Tried on 5 computers win10/win11, all have same problem. .NET is of course installed by system.

**Comment by Blackhatfrance** [comment]
It's a trojan guys

**Comment by Xcertik-Realist** [comment]
its an info stealer guys your all gonna get drained !!!
it instals malware on your PC
